//
//  UncorkedEngine.swift
//  UncorkedKit
//
//  This file is part of Uncorked.
//
//  Uncorked is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Uncorked is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Uncorked.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation
import SemanticVersion

// MARK: - Errors

public enum UncorkedEngineError: LocalizedError {
    case appVersionTooOld(required: String)
    case insufficientDiskSpace(needed: Int64, available: Int64)

    public var errorDescription: String? {
        switch self {
        case .appVersionTooOld(let required):
            return "Uncorked \(required) or later is required. Please update the app first."
        case .insufficientDiskSpace(let needed, let available):
            let fmt = ByteCountFormatter()
            fmt.countStyle = .file
            return "Not enough disk space. Need \(fmt.string(fromByteCount: needed)), "
                + "have \(fmt.string(fromByteCount: available)) available."
        }
    }
}

// MARK: - Installed engine state

/// Written to engine-version.json in Application Support after a successful install.
public struct InstalledEngineVersion: Codable {
    /// Uncorked engine version string (matches EngineManifest.engineVersion).
    public var engineVersion: String
    /// Upstream Gcenx release tag (matches EngineManifest.upstreamTag).
    public var upstreamTag: String
}

// MARK: - Engine manager

public class UncorkedEngine {
    /// ~/Library/Application Support/Uncorked
    public static let applicationFolder = FileManager.default.urls(
        for: .applicationSupportDirectory, in: .userDomainMask
    )[0].appending(path: Bundle.uncorkedBundleIdentifier)

    /// ~/Library/Application Support/Uncorked/Libraries
    /// Used by DXVK, winetricks, and other per-prefix managed content.
    public static let libraryFolder = applicationFolder.appending(path: "Libraries")

    /// ~/Library/Application Support/Uncorked/Engine
    /// The downloaded and installed Wine engine lives here.
    public static let engineFolder = applicationFolder.appending(path: "Engine")

    /// ~/Library/Application Support/Uncorked/Engine/bin
    /// All subprocess launches reference uncorked64 from this directory.
    public static let binFolder: URL = engineFolder.appending(path: "bin")

    /// ~/Library/Application Support/Uncorked/engine-version.json
    private static let versionStateURL = applicationFolder.appending(path: "engine-version.json")

    // MARK: - State

    public static func isEnginePresent() -> Bool {
        guard let state = readVersionState() else { return false }
        // Confirm the uncorked64 wrapper (generated by the engine pipeline) is present.
        let uncorked64 = binFolder.appending(path: "uncorked64")
        return !state.engineVersion.isEmpty
            && FileManager.default.fileExists(atPath: uncorked64.path)
    }

    public static func engineVersion() -> SemanticVersion? {
        guard let state = readVersionState() else { return nil }
        return parseVersion(state.engineVersion)
    }

    public static func installedEngineState() -> InstalledEngineVersion? {
        readVersionState()
    }

    private static func readVersionState() -> InstalledEngineVersion? {
        guard let data = try? Data(contentsOf: versionStateURL) else { return nil }
        return try? JSONDecoder().decode(InstalledEngineVersion.self, from: data)
    }

    // MARK: - Phased install API (used by EngineSetupView)

    /// Fetches the signed manifest from data.grubwire.io and verifies its signature.
    public static func fetchManifest() async throws -> EngineManifest {
        try await EngineManifestClient.fetch()
    }

    /// Downloads the archive for `manifest`, streaming bytes to a temp file.
    /// `progress` is called with (bytesWritten, totalExpected); totalExpected may be -1 if unknown.
    public static func downloadArchive(
        manifest: EngineManifest,
        progress: @escaping @Sendable (Int64, Int64) -> Void
    ) async throws -> URL {
        guard let url = URL(string: manifest.url) else { throw URLError(.badURL) }
        let (byteStream, response) = try await URLSession.shared.bytes(from: url)
        guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
            throw URLError(.badServerResponse)
        }
        let expected = http.expectedContentLength

        let dest = FileManager.default.temporaryDirectory
            .appending(path: UUID().uuidString + ".tar.xz")
        FileManager.default.createFile(atPath: dest.path, contents: nil)
        let handle = try FileHandle(forWritingTo: dest)

        var buf = Data(capacity: 65536)
        var written: Int64 = 0
        for try await byte in byteStream {
            buf.append(byte)
            if buf.count >= 65536 {
                try handle.write(contentsOf: buf)
                written += Int64(buf.count)
                buf.removeAll(keepingCapacity: true)
                progress(written, expected)
            }
        }
        if !buf.isEmpty {
            try handle.write(contentsOf: buf)
            written += Int64(buf.count)
            progress(written, expected)
        }
        try handle.close()
        return dest
    }

    /// Verifies the archive SHA-256 against the manifest, then extracts and installs.
    /// Checks minAppVersion and available disk space before proceeding.
    public static func verifyAndInstall(archive: URL, manifest: EngineManifest) async throws {
        defer { try? FileManager.default.removeItem(at: archive) }

        // Check that the running app version meets the manifest's minimum requirement.
        let appVersionString = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "0.0.0"
        let appVersion = parseVersion(appVersionString)
        let minRequired = parseVersion(manifest.minAppVersion)
        guard appVersion >= minRequired else {
            throw UncorkedEngineError.appVersionTooOld(required: manifest.minAppVersion)
        }

        // Check available disk space against the manifest's declared uncompressed engine size.
        try FileManager.default.createDirectory(at: applicationFolder, withIntermediateDirectories: true)
        let attrs = try FileManager.default.attributesOfFileSystem(forPath: applicationFolder.path)
        if let freeSpace = attrs[.systemFreeSize] as? Int64, freeSpace < manifest.sizeBytes {
            throw UncorkedEngineError.insufficientDiskSpace(needed: manifest.sizeBytes, available: freeSpace)
        }

        try EngineManifestClient.verifyArchive(at: archive, against: manifest)
        try await extract(archive: archive, manifest: manifest)
    }

    // MARK: - Extraction

    private static func extract(archive: URL, manifest: EngineManifest) async throws {
        try FileManager.default.createDirectory(at: applicationFolder, withIntermediateDirectories: true)

        let tempDir = applicationFolder.appending(path: "_extract_tmp")
        if FileManager.default.fileExists(atPath: tempDir.path) {
            try FileManager.default.removeItem(at: tempDir)
        }
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

        try Tar.untar(tarBall: archive, toURL: tempDir)

        let engineRoot = try findEngineRoot(in: tempDir)
        try clearQuarantine(at: engineRoot)

        // Atomic rename: remove old engine then move the extracted tree into place.
        if FileManager.default.fileExists(atPath: engineFolder.path) {
            try FileManager.default.removeItem(at: engineFolder)
        }
        try FileManager.default.moveItem(at: engineRoot, to: engineFolder)
        try? FileManager.default.removeItem(at: tempDir)

        try writeVersionState(InstalledEngineVersion(
            engineVersion: manifest.engineVersion,
            upstreamTag: manifest.upstreamTag
        ))
    }

    private static func findEngineRoot(in dir: URL) throws -> URL {
        let contents = try FileManager.default.contentsOfDirectory(
            at: dir, includingPropertiesForKeys: [.isDirectoryKey], options: .skipsHiddenFiles
        )
        // The archive contains one top-level directory named "engine/".
        if let match = contents.first(where: {
            FileManager.default.fileExists(atPath: $0.appending(path: "bin/wine64").path)
            || FileManager.default.fileExists(atPath: $0.appending(path: "bin/wine").path)
        }) { return match }
        guard let first = contents.first else { throw CocoaError(.fileNoSuchFile) }
        return first
    }

    private static func clearQuarantine(at url: URL) throws {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/xattr")
        process.arguments = ["-dr", "com.apple.quarantine", url.path]
        try process.run()
        process.waitUntilExit()
    }

    private static func writeVersionState(_ state: InstalledEngineVersion) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(state)
        try data.write(to: versionStateURL)
    }

    // MARK: - Uninstall

    public static func uninstall() {
        try? FileManager.default.removeItem(at: engineFolder)
        try? FileManager.default.removeItem(at: versionStateURL)
    }

    // MARK: - Update check

    /// Returns whether a newer engine is available and the remote version string.
    public static func shouldUpdateEngine() async -> (Bool, SemanticVersion) {
        guard let local = engineVersion() else { return (false, SemanticVersion(0, 0, 0)) }
        guard let manifest = try? await EngineManifestClient.fetch() else {
            return (false, SemanticVersion(0, 0, 0))
        }
        let remote = parseVersion(manifest.engineVersion)
        return local < remote ? (true, remote) : (false, remote)
    }

    // MARK: - Migration cleanup

    /// Removes a stale pre-managed engine left at Libraries/Wine by older builds.
    /// Preserves all bottles and wineprefixes. Safe to call on every launch.
    public static func removeLegacyEngineIfNeeded() {
        let flagKey = "uncorkedLegacyEngineRemoved"
        guard !UserDefaults.standard.bool(forKey: flagKey) else { return }
        UserDefaults.standard.set(true, forKey: flagKey)

        // The legacy engine lived at Libraries/Wine and had no engine-version.json.
        // The new managed engine always writes engine-version.json, so absence of
        // that file is the reliable signal that this is a stale pre-managed install.
        let stale = libraryFolder.appending(path: "Wine")
        guard FileManager.default.fileExists(atPath: stale.path)
                && !FileManager.default.fileExists(atPath: versionStateURL.path) else { return }
        try? FileManager.default.removeItem(at: stale)
    }

    // MARK: - Helpers

    public static func parseVersion(_ tag: String) -> SemanticVersion {
        let parts = tag.components(separatedBy: CharacterSet.decimalDigits.inverted)
            .filter { !$0.isEmpty }
        let major = parts.first.flatMap { Int($0) } ?? 0
        let minor = parts.dropFirst().first.flatMap { Int($0) } ?? 0
        let patch = parts.dropFirst(2).first.flatMap { Int($0) } ?? 0
        return SemanticVersion(major, minor, patch)
    }
}
