//
//  FailureReportBuilder.swift
//  Crosswire
//
//  This file is part of Crosswire.
//
//  Crosswire is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Crosswire is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Crosswire.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation
import CrosswireKit

/// Builds the URL that opens a pre-filled GitHub issue on grubwire/crosswire
/// for an abnormal program exit. Pure function — no UI, no side effects.
///
/// Never auto-submits. The URL just opens the "new issue" form in the
/// browser with title + body filled in; the user reviews and clicks
/// "Submit new issue" themselves. This is a hard requirement from the
/// failure-reporting spec.
enum FailureReportBuilder {
    private static let repoBase = "https://github.com/grubwire/crosswire"
    /// Hard cap. GitHub's URL-prefilled body limit is ~7-8 KB before the
    /// server rejects it; we keep well under that.
    private static let maxBodyChars = 6000
    /// Tail size for the run log.
    private static let logTailLines = 150

    static func issueURL(for report: ProgramRunReport) -> URL? {
        let exeName = report.executableURL.deletingPathExtension().lastPathComponent
        let title = "[crash] \(exeName) exited \(report.exitCode) in \(report.bottleDisplayName)"
        let body = buildBody(for: report)

        var components = URLComponents(string: "\(repoBase)/issues/new")
        components?.queryItems = [
            URLQueryItem(name: "title", value: title),
            URLQueryItem(name: "body", value: body),
            URLQueryItem(name: "labels", value: "crash-report")
        ]
        return components?.url
    }

    private static func buildBody(for report: ProgramRunReport) -> String {
        var sections: [String] = []

        sections.append("**App:** `\(report.executableURL.lastPathComponent)`")
        sections.append("**Bottle:** \(report.bottleDisplayName)")
        sections.append("**Exit code:** \(report.exitCode)")
        sections.append("**Ran for:** \(String(format: "%.1f", report.duration))s")

        sections.append("\n### Environment")
        sections.append(environmentSection(for: report))

        sections.append("\n### Run log tail (last \(logTailLines) lines)")
        sections.append("```")
        sections.append(logTail(from: report.logFileURL))
        sections.append("```")

        sections.append("\n---")
        sections.append("_Auto-generated by Crosswire's failure-report dialog. "
                        + "Edit the title / body before submitting if you have more context._")

        var body = sections.joined(separator: "\n")
        if body.count > maxBodyChars {
            // Trim the log section first; preserve the meta + env header
            let suffix = "\n\n_(log truncated to fit GitHub's URL body limit; "
                + "see full log at \(report.logFileURL?.path ?? "the run log path") for the rest)_"
            body = String(body.prefix(maxBodyChars - suffix.count)) + suffix
        }
        return body
    }

    private static func environmentSection(for report: ProgramRunReport) -> String {
        var lines: [String] = []
        let osVersion = ProcessInfo.processInfo.operatingSystemVersion
        lines.append("- **macOS:** "
                     + "\(osVersion.majorVersion).\(osVersion.minorVersion).\(osVersion.patchVersion)")
        if let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String,
           let build = Bundle.main.infoDictionary?["CFBundleVersion"] as? String {
            lines.append("- **Crosswire:** \(appVersion) (build \(build))")
        }
        if let engineVersion = CrosswireEngine.engineVersion()?.description {
            lines.append("- **Engine:** \(engineVersion)")
        }
        // Bottle config from disk so the report works even if the Bottle
        // object is gone by the time the user clicks Report.
        let metadataURL = report.bottleURL
            .appending(path: "Metadata")
            .appendingPathExtension("plist")
        if let settings = try? BottleSettings.decode(from: metadataURL) {
            lines.append("- **Windows version:** \(settings.windowsVersion.pretty())")
            lines.append("- **DXVK:** \(settings.dxvk ? "on" : "off")")
        }
        return lines.joined(separator: "\n")
    }

    private static func logTail(from url: URL?) -> String {
        guard let url else { return "(no log file located)" }
        guard let data = try? Data(contentsOf: url),
              let text = String(data: data, encoding: .utf8)
        else { return "(could not read log at \(url.path))" }
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        let tail = lines.suffix(logTailLines)
        return tail.joined(separator: "\n")
    }
}
